name: sadtrombonebutton
description: "Enjoy your failures by plaing the classic womp womp womp womp sound effect."
publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.0
  package_info_plus: ^8.3.0
  share_plus: ^11.0.0
  
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/audio/sadtrombone_soundeffect_1.wav
    - assets/images/sadtrombonebutton.png
