name: sadtrombonebutton
description: "Enjoy your failures by plaing the classic womp womp womp womp sound effect."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  package_info_plus: ^8.0.0
  share_plus: ^9.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/sadtrombone_soundeffect_1.wav
    - assets/images/sadtrombonebutton.png
